### ISSUE TITLE
Change inline text with string constant

### ISSUE THREAD

**Issue by ghost** [arsesssssss/home#1]
For example, such code:

`System.out.printf("Введите размер квадратной матрицы (целое число от %d до %d): "`

must be replaced with this code:

`private static final String cInputPromptFormat =
            "Введите размер квадратной матрицы (целое число от %d до %d): ";`

...

`System.out.printf(
                    cInputPromptFormat, cMatrixSizeMin, cMatrixSizeMax);`

**Comment by arsesssssss** [comment]
done
